services:
  - type: web
    name: Grading_management_system
    env: python
    pythonVersion: 3.12
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn main:app
